// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void xinglv_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Container1;
void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel2;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_478574081);    // assets/R-C.png
LV_IMG_DECLARE(ui_img_1901514184);    // assets/Snipaste_2024-05-06_19-15-14.png



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
